### Instalações

### Importando bibliotecas

In [3]:
!pip install scikit-learn

In [4]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

### Leitura dos dados

In [5]:
df = pd.read_csv("Skyserver_SQL2_27_2018 6_51_39 PM.csv")

In [6]:
df.head()

objid          ra       dec         u         g         r         i  \
0  1.237650e+18  183.531326  0.089693  19.47406  17.04240  15.94699  15.50342   
1  1.237650e+18  183.598370  0.135285  18.66280  17.21449  16.67637  16.48922   
2  1.237650e+18  183.680207  0.126185  19.38298  18.19169  17.47428  17.08732   
3  1.237650e+18  183.870529  0.049911  17.76536  16.60272  16.16116  15.98233   
4  1.237650e+18  183.883288  0.102557  17.55025  16.26342  16.43869  16.55492   

          z  run  rerun  camcol  field     specobjid   class  redshift  plate  \
0  15.22531  752    301       4    267  3.722360e+18    STAR -0.000009   3306   
1  16.39150  752    301       4    267  3.638140e+17    STAR -0.000055    323   
2  16.80125  752    301       4    268  3.232740e+17  GALAXY  0.123111    287   
3  15.90438  752    301       4    269  3.722370e+18    STAR -0.000111   3306   
4  16.61326  752    301       4    269  3.722370e+18    STAR  0.000590   3306   

     mjd  fiberid  
0  54922      491  
1  51615      541  
2  52023      513  
3  54922      510  
4  54922      512

In [7]:
contagem_tipos = df['class'].value_counts()
print(contagem_tipos)

class
GALAXY    4998
STAR      4152
QSO        850
Name: count, dtype: int64


### Treinamento do modelo

In [8]:
df = df.dropna(subset=['class'])

X = df[['ra', 'dec', 'u', 'g', 'r', 'i', 'z', 'redshift']]
y = df['class'].map({'STAR': 0, 'GALAXY': 1, 'QSO': 2, 'OTHER': 3})

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [9]:
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

In [10]:
print("Acurácia:", accuracy_score(y_test, y_pred))

print("\nRelatório de Classificação:\n", classification_report(y_test, y_pred))

print("\nMatriz de Confusão:\n", confusion_matrix(y_test, y_pred))

Acurácia: 0.9905

Relatório de Classificação:
               precision    recall  f1-score   support

           0       0.99      1.00      1.00       814
           1       0.99      0.99      0.99       996
           2       0.98      0.95      0.97       190

    accuracy                           0.99      2000
   macro avg       0.99      0.98      0.98      2000
weighted avg       0.99      0.99      0.99      2000


Matriz de Confusão:
 [[814   0   0]
 [  6 987   3]
 [  0  10 180]]


### Testando

In [22]:
exemplo = pd.DataFrame([[17.5, 16.2, 15.8, 15.5, 735, 300, 3, 260]],
                            columns=['ra', 'dec', 'u', 'g', 'r', 'i', 'z', 'redshift'])

previsao = model.predict(exemplo)

# Imprimir a previsão
print(f"A previsão do modelo para o exemplo é: {previsao}")


A previsão do modelo para o exemplo é: [2]


In [20]:
exemplos_aleatorios = pd.DataFrame(np.random.rand(5, 8), columns=['ra', 'dec', 'u', 'g', 'r', 'i', 'z', 'redshift'])

previsoes = model.predict(exemplos_aleatorios)

exemplos_aleatorios['previsao'] = previsoes
print(exemplos_aleatorios)

         ra       dec         u         g         r         i         z  \
0  0.809543  0.670315  0.070203  0.092174  0.583791  0.891391  0.685567   
1  0.267891  0.993768  0.053010  0.554406  0.287605  0.284841  0.355393   
2  0.198705  0.738898  0.158071  0.895920  0.202078  0.144756  0.279011   
3  0.128202  0.250092  0.511452  0.347403  0.384716  0.569219  0.855070   
4  0.538708  0.128693  0.376770  0.836335  0.054904  0.863502  0.005582   

   redshift  previsao  
0  0.699222         1  
1  0.127536         1  
2  0.227744         1  
3  0.636132         1  
4  0.482997         1  
